### ISSUE TITLE
Automatically organize subdeck media into folders

### ISSUE THREAD

**Issue by sugarycat** [abdnh/anki-media-exporter#1]
Hello, thank you so much for this add-on.

I have a deck with lots of subdecks and was hoping to export all of the media, with the media for each subdeck automatically organized into its own folders. 
Would you be willing to consider adding this type of feature?

Thank you!

**Comment by abdnh** [comment]
Will look into this in the next release.

**Comment by abdnh** [comment]
This is now possible by setting the `organize_into_subfolders` config option to `true`. I may expose this in the GUI in the future.
