### ISSUE TITLE
static files not included

### ISSUE THREAD

**Issue by CravingCrates** [abdnh/anki-media-exporter#3]
You might be interested in this issue: https://github.com/CravingCrates/AnkiCollab-Plugin/issues/14

I believe (untested) the same issue exists in this project since I only copied your mechanism. I will see if I can find time next week to investigate it

**Comment by abdnh** [comment]
Thanks for the heads-up Jan!

Looks like we have to re-implement the regexes used by Anki since they are not exposed on the Python side. I'll try to look into this soon, but let me know if you get to fix it for AnkiCollab before that.

**Comment by abdnh** [comment]
Fixed in #5
